#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

if grep -q hypervisor /proc/cpuinfo; then
  xrandr --output Virtual1 --mode 1280x720 --rate 60
fi

xcompmgr &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
feh --bg-scale /home/romain/Pictures/pexels-lumn-167698.jpg
/usr/local/bin/dwmblocks &
/usr/bin/dunst &
exec dwm
